"use client";

import { ResourcePage } from "@/components/resource-page";
import { StatusBadge } from "@/components/status-badge";
import { DetailLink } from "@/components/text";
import { formatDate, formatDateTime } from "@/lib/format";
import type { Digest } from "@/lib/types";

export default function DigestsPage() {
  return (
    <ResourcePage<Digest>
      columns={[
        {
          header: "Title",
          cell: (row) => <DetailLink href={`/digests/${row.id}`} label={row.title} />,
        },
        { header: "Date", cell: (row) => formatDate(row.digest_date) },
        { header: "Status", cell: (row) => <StatusBadge value={row.status} /> },
        { header: "Selected", cell: (row) => row.total_selected },
        { header: "Critical", cell: (row) => row.critical_count },
        { header: "Important", cell: (row) => row.important_count },
        { header: "Monitor", cell: (row) => row.monitor_count },
        { header: "Created", cell: (row) => formatDateTime(row.created_at) },
      ]}
      description="Daily briefing digests generated by the news pipeline."
      emptyLabel="No digests found."
      filters={[
        {
          key: "status",
          label: "Status",
          type: "select",
          options: ["draft", "finalized", "archived"].map((value) => ({ label: value, value })),
        },
        { key: "digest_date", label: "Digest Date", type: "date" },
        { key: "created_from", label: "Created From", type: "datetime-local" },
        { key: "created_to", label: "Created To", type: "datetime-local" },
      ]}
      path="/api/v1/digests"
      title="Daily Briefings"
    />
  );
}
